### ISSUE TITLE
Server reset / reinstate Visual.tools 

### ISSUE THREAD

**Issue by johnkellas** [christopherreay/thisEqualsThat_frontEnd#135]
Visual.Tools is not running 
<img width="768" alt="screen shot 2017-07-12 at 15 33 36" src="https://user-images.githubusercontent.com/20540827/28123058-e4b90bd0-6717-11e7-8dbb-900d47ec69b4.png">
Please re-instate

**Comment by christopherreay** [comment]
yeah. The actual server has gone down since last night
ᐧ

Be prepared to have your predictions come true

**Comment by johnkellas** [comment]
Whagwan with that?

**Comment by christopherreay** [comment]
no idea. ive rebooted it and brought production back up.

Really I need to rebuild the whole server onto a newer version of ubunuts

not a huge deal

**Comment by johnkellas** [comment]
Thank you for reinstating. Kudos. It works now. :) <3

**Comment by christopherreay** [comment]
also I put bertonbeil server back up

**Comment by johnkellas** [comment]
Sweet
