### ISSUE TITLE
Set default view of out put fields as colapsed (or colapsing)

### ISSUE THREAD

**Issue by johnkellas** [christopherreay/thisEqualsThat_frontEnd#60]
If poss make the arrow control the accordion functionality - + or instead of the header

**Comment by johnkellas** [comment]
My preference is having the collapsable fields collapsed on arrival. Activated / opened through clicking on the little arrow

**Comment by bertonbeil** [comment]
all changes here e4f316005b8c55bf91ee8440f760aece5c004eb4

**Comment by bertonbeil** [comment]
@johnkellas I think this one done(but there are some bug panell collapsing when you clicked on parent panel title and this panell title)
