### ISSUE TITLE
Remove the globe widget - or add accreditation

### ISSUE THREAD

**Issue by johnkellas** [christopherreay/thisEqualsThat_frontEnd#62]
"Google Chrome Experiment - Google Data Arts Team"

**Comment by christopherreay** [comment]
how?

**Comment by johnkellas** [comment]
Thanks to the stuff you must have done not somewhile ago
<img width="738" alt="screen shot 2017-06-02 at 17 14 08" src="https://cloud.githubusercontent.com/assets/20540827/26734742/103e1c12-47b7-11e7-9cb1-de10ee046d16.png">
