### ISSUE TITLE
Add a model info button

### ISSUE THREAD

**Issue by johnkellas** [christopherreay/thisEqualsThat_frontEnd#64]
!model information

There are assumptions in each model. EG. are loads of types of coal ; energy distribution loss factor in lightbulb model etc. - it would be good to havea place where the assumptions are documented - not on initial display - but available readily enough.

**Comment by bertonbeil** [comment]
I have an idea about this!

**Comment by christopherreay** [comment]
feel free to do whatever you woul dlike andrew.

I have added "tooltip" to the suite of tools in the bootstrap js file, and added a rule for tooltips in the commit above, into thisEqualsThat.js around line 1666
