### ISSUE TITLE
No current implementation of frame of reference selector

### ISSUE THREAD

**Issue by johnkellas** [christopherreay/thisEqualsThat_frontEnd#68]

**Comment by bertonbeil** [comment]
@johnkellas please can you describe it more detailed ?
thanks

**Comment by christopherreay** [comment]
I think I have seen this in the interface @bertonbeil  has made... Is this true?

**Comment by bertonbeil** [comment]
@christopherreay, @johnkellas please describe this one more details and I'll fix it

**Comment by christopherreay** [comment]
Well there is an implmenetation, its just a checkbox

andrew These buttons:

![toggles thisequalsthat](https://cloud.githubusercontent.com/assets/239550/22479803/0a9d0ba4-e7e7-11e6-9e16-cc79ce6da861.png)

**Comment by christopherreay** [comment]
Oops Nope, I was talking nonsense

The Frame of reference selector, as you say, has no implementation at all

I will make one
