### ISSUE TITLE
fix css so that spinner animations are still there

### ISSUE THREAD

**Issue by christopherreay** [christopherreay/thisEqualsThat_frontEnd#74]
checkout the animations on visual.tools/thisEqualsThat

on dev.visual.tools/thisEqualsThat the animations hav stopped.

This is just because you have removed the css classes that enable the animations

**Comment by bertonbeil** [comment]
I was commend js lines with .toggleClass('spinner') I fix it in my last commit c79d806776523e55faefdc677c731e39244d2085

**Comment by christopherreay** [comment]
Ok done it

**Comment by christopherreay** [comment]
yes, you comment them out.

If you want to change the way it looks, then asssign the ...Spinner classes to other elements and play with the CSS. But there needs to be some indication of work
