### ISSUE TITLE
Rendering of clones in percentage widget

### ISSUE THREAD

**Issue by johnkellas** [christopherreay/thisEqualsThat_frontEnd#83]
When I try to build multiple percentage groups by colour i can no longer change the amount of people. Seems unresponsive. it would be great if this could be fixed 
<img width="909" alt="screen shot 2017-05-06 at 00 03 23" src="https://cloud.githubusercontent.com/assets/20540827/25767233/7bff89a0-31ef-11e7-8ce2-cf1a53234f1e.png">

**Comment by johnkellas** [comment]
Meh, is now working - soz

**Comment by christopherreay** [comment]
Proabaly this was that the server was broken by someone like me whilst you were doing it. Happens sometimes.
